name: Create .env File

on: [push, pull_request, workflow_dispatch]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify your Node.js version

    - name: Set environment variables from GitHub secrets
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Generate .env file
      run: |
        chmod +x generate-env.sh
        ./generate-env.sh

    - name: Verify .env file creation
      run: cat .env