name: Create .env File

on: [push, pull_request, workflow_dispatch]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify your Node.js version

    - name: Set environment variables from GitHub secrets
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
        
    - name: Set environment variables from GitHub env variables
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(vars) }}

    - name: Generate .env file
      run: |
        #chmod +x generate-env.sh
        #./generate-env.sh
        for SECRET_NAME in $(cat .env.example | cut -d= -f1); do
          SECRET_VALUE="${!SECRET_NAME}"
          echo "${SECRET_NAME#${PREFIX}}=${SECRET_VALUE}" >> .env
        done

    - name: Verify .env file creation
      run: cat .env

    - name: Commit the file
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .env
        git commit -m "updating file"
        git push
